name: tabib
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.8
  flutter_svg: ^2.0.10+1
  intl_phone_field: ^3.2.0
  table_calendar: ^3.1.2
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.2
  introduction_screen: ^3.1.14
  provider: ^6.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/