// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbnxSDHxPYinW9T8QZOq9nfnn30JGt4Ic',
    appId: '1:309100222597:web:9661a4b2ba1e2c1bc5b1ec',
    messagingSenderId: '309100222597',
    projectId: 'tabib-2bc4a',
    authDomain: 'tabib-2bc4a.firebaseapp.com',
    storageBucket: 'tabib-2bc4a.firebasestorage.app',
    measurementId: 'G-0MP09DBYN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsineKK4ObBb8ebHOTL1RcfJttBBfZ5Fk',
    appId: '1:309100222597:android:2d873bd1692b3621c5b1ec',
    messagingSenderId: '309100222597',
    projectId: 'tabib-2bc4a',
    storageBucket: 'tabib-2bc4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBesXiPKupD9QB7G9COn5TPDZAj_MgfpJQ',
    appId: '1:309100222597:ios:e34c3a5ff9c929ffc5b1ec',
    messagingSenderId: '309100222597',
    projectId: 'tabib-2bc4a',
    storageBucket: 'tabib-2bc4a.firebasestorage.app',
    iosBundleId: 'com.example.tabib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBesXiPKupD9QB7G9COn5TPDZAj_MgfpJQ',
    appId: '1:309100222597:ios:e34c3a5ff9c929ffc5b1ec',
    messagingSenderId: '309100222597',
    projectId: 'tabib-2bc4a',
    storageBucket: 'tabib-2bc4a.firebasestorage.app',
    iosBundleId: 'com.example.tabib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbnxSDHxPYinW9T8QZOq9nfnn30JGt4Ic',
    appId: '1:309100222597:web:c06bcb593d23c4aac5b1ec',
    messagingSenderId: '309100222597',
    projectId: 'tabib-2bc4a',
    authDomain: 'tabib-2bc4a.firebaseapp.com',
    storageBucket: 'tabib-2bc4a.firebasestorage.app',
    measurementId: 'G-Y86R4EH7MC',
  );
}
